 

version: '3.9'

services:
  angular-app:
    image: httpd:alpine
    container_name: meu-angular-psn-store-app
    ports:
      - '8083:80'
    volumes:
      - ./dist/angular-psn-store/browser:/usr/local/apache2/htdocs/   
    networks:
      - angular-network

networks:
  angular-network:
    driver: bridge